Repository threema-ch/threema-web, pull requests merged in 2018-11, with the labels that each got.

#664 Document new translation workflow
  README.md
  RELEASING.md
  TRANSLATING.md
  public/i18n/README.md
Labels: chore

#666 Don't validate `args` for create/group & create/distributionList
  src/services/webclient.ts
Labels: bug

#667 Member list editor: Handle inactive contacts
  src/directives/contact_badge.ts
  src/directives/member_list_editor.ts
  src/sass/components/_receiver_badge.scss
Labels: bug, ui

#668 UI Tests
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  src/directives/compose_area.ts
  src/filters.ts
  src/sass/sections/_compose_area.scss
  tests/ui/compose_area.html
  tests/ui/compose_area.ts
  tests/ui/main.ts
  tests/ui/run.sh
  tests/ui/run.ts
Labels: chore

#669 Replace Test Cafe with Selenium
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  src/directives/compose_area.ts
  src/helpers.ts
  tests/ui/run.sh
  tests/ui/run.ts
Labels: Testing

#673 ComposeArea: Fix cursor pos when inserting emoji
  src/directives/compose_area.ts
  tests/ui/run.ts
Labels: bug

#682 Properly report push promise rejections
  src/services/push.ts
  src/services/webclient.ts
Labels: bug
