Repository threema-ch/threema-web, pull requests merged in 2018-10, with the labels that each got.

#602 Trigger loading messages when opening an empty conversation
  src/partials/messenger.ts
  src/services/webclient.ts
Labels: bug

#610 Fix largeSingleEmoji setting
  src/directives/message_text.ts
Labels: bug

#590 New markup parser
  src/filters.ts
  src/markup_parser.ts
  tests/filters.js
  tests/ts/main.ts
  tests/ts/markup_parser.ts
Labels: awaiting feedback, bug

#626 Copy to clipboard: Workaround for Safari on iOS
  src/directives/message.ts
  src/helpers/browser_info.ts
Labels: bug

#625 Only show WebRTC troubleshooting tips when appropriate
  src/partials/welcome.html
  src/partials/welcome.ts
Labels: optimization, ui

#624 StateService: Allow more time for loading initial data
  src/services/state.ts
Labels: optimization, ui

#630 MarkupParser: Fix bug with double markup chars
  src/markup_parser.ts
  tests/ts/markup_parser.ts
Labels: bug

#636 Accessibility improvements
  src/app.ts
  src/components/toggle_button.ts
  src/partials/welcome.html
Labels: accessibility

#638 Fix updating of message caption
  src/directives/latest_message.html
  src/directives/latest_message.ts
  src/directives/message_icon.ts
  src/directives/message_media.ts
  src/directives/message_text.ts
Labels: bug

#637 Clear typing flag when receiving message
  src/services/webclient.ts
  src/threema.d.ts
  src/threema/container.ts
Labels: bug

#642 Clear mediabox data on state transitions
  src/directives/mediabox.ts
  src/directives/message_media.ts
Labels: bug, privacy

#643 Fix updating of avatars in contact autocomplete box
  src/directives/avatar.ts
  src/directives/contact_badge.ts
Labels: bug

#649 Latest message text: Show "GIF" for GIFs
  src/directives/message_text.ts
Labels: ui

#650 MimeService: Add null check to getKey
  src/services/mime.ts
Labels: bug

#656 Fix labels for button bar in contact or group details view.
  src/partials/messenger.receiver.html
Labels: accessibility

#661 Contacts: Exclude hidden receivers
  src/filters.ts
  src/partials/messenger.navigation.html
  src/partials/messenger.ts
Labels: enhancement
