Repository threema-ch/threema-web, pull requests merged in 2021-01, with the labels that each got.

#1016 Update copyright headers for 2021
  README.md
  index.html
  src/app.ts
  src/bootstrap.ts
  src/partials/dialog.about.html
  tests/bootstrap.ts
  tests/ts/bootstrap.ts
  tests/ts/confidential_helpers.ts
  tests/ts/containers.ts
  tests/ts/crypto_helpers.ts
  tests/ts/emoji_helpers.ts
  tests/ts/helpers.ts
  tests/ts/logger_helpers.ts
  tests/ts/main.ts
  tests/ts/markup_parser.ts
  tests/ts/password_strength_helpers.ts
  tests/ui/bootstrap.ts
  tests/ui/compose_area.ts
  tests/ui/main.ts
  tests/ui/run.ts
  troubleshoot/index.html
  troubleshoot/log.html
  webpack.prod.js
Labels: chore

#1014 Fix logic for determining whether a point in time was yesterday
  src/filters.ts
  tests/filters.js
Labels: awaiting feedback, bug

#1018 Update favicons and logos
  index.html
  public/browserconfig.xml
  public/img/favicon/android-chrome-192x192.png
  public/img/favicon/android-chrome-512x512.png
  public/img/favicon/android-icon-144x144.png
  public/img/favicon/android-icon-192x192.png
  public/img/favicon/android-icon-36x36.png
  public/img/favicon/android-icon-48x48.png
  public/img/favicon/android-icon-72x72.png
  public/img/favicon/android-icon-96x96.png
  public/img/favicon/apple-icon-114x114.png
  public/img/favicon/apple-icon-120x120.png
  public/img/favicon/apple-icon-144x144.png
  public/img/favicon/apple-icon-152x152.png
  public/img/favicon/apple-icon-180x180.png
  public/img/favicon/apple-icon-57x57.png
  public/img/favicon/apple-icon-60x60.png
  public/img/favicon/apple-icon-72x72.png
  public/img/favicon/apple-icon-76x76.png
  public/img/favicon/apple-touch-icon-120x120.png
  public/img/favicon/apple-touch-icon-152x152.png
  public/img/favicon/apple-touch-icon-180x180.png
  public/img/favicon/apple-touch-icon-60x60.png
  public/img/favicon/apple-touch-icon-76x76.png
  public/img/favicon/apple-touch-icon.png
  public/img/favicon/favicon-16x16-error.png
  public/img/favicon/favicon-16x16-unread.png
  public/img/favicon/favicon-16x16-warning.png
  public/img/favicon/favicon-16x16.png
  public/img/favicon/favicon-32x32-error.png
  public/img/favicon/favicon-32x32-unread.png
  public/img/favicon/favicon-32x32-warning.png
  public/img/favicon/favicon-32x32.png
  public/img/favicon/favicon-96x96.png
  public/img/favicon/favicon.ico
  public/img/favicon/ms-icon-144x144.png
  public/img/favicon/ms-icon-150x150.png
  public/img/favicon/ms-icon-310x310.png
  public/img/favicon/ms-icon-70x70.png
  public/img/favicon/mstile-150x150.png
  public/img/favicon/safari-pinned-tab.svg
  public/img/threema-64x64.png
  public/manifest.webmanifest
Labels: chore, ui

#1019 Use Ctrl+Enter to submit instead of Shift+Enter
  public/i18n/cs.json
  public/i18n/de.json
  public/i18n/en.json
  public/i18n/es.json
  public/i18n/fr.json
  public/i18n/nl.json
  public/i18n/pl.json
  public/i18n/sk.json
  public/i18n/uk.json
  public/i18n/zh.json
  src/directives/compose_area.ts
  src/partials/dialog.settings.html
  src/services/settings.ts
  src/threema.d.ts
Labels: optimization

#1020 Shorten quotes if too long
  src/directives/compose_area.ts
  src/partials/messenger.ts
  src/services/webclient.ts
  src/threema.d.ts
Labels: bug

#1023 Fix Safari "pinned tab" icon
  public/img/favicon/safari-pinned-tab.svg
Labels: bug

#1024 Extract markup parser into standalone library
  package-lock.json
  package.json
  src/filters.ts
  src/markup_parser.ts
  tests/ts/main.ts
  tests/ts/markup_parser.ts
Labels: chore
